steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'europe-west1-docker.pkg.dev/shared-images-nonprod/docker-images/kubectl-run-job:latest'
  - '-t'
  - 'europe-west1-docker.pkg.dev/shared-images-nonprod/docker-images/kubectl-run-job:${SHORT_SHA}'
  - '.'

images:
- 'europe-west1-docker.pkg.dev/shared-images-nonprod/docker-images/kubectl-run-job:latest'
- 'europe-west1-docker.pkg.dev/shared-images-nonprod/docker-images/kubectl-run-job:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
